<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sws_xsd="http://webservices.sabre.com/sabreXML/2011/10" xmlns:sws="https://webservices.sabre.com/websvc" xmlns:eb="http://www.ebxml.org/namespaces/messageHeader" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" targetNamespace="https://webservices.sabre.com/websvc">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://webservices.sabre.com/sabreXML/2011/10" schemaLocation="HotelRateDescriptionLLS2.3.0RQRS.xsd"/>
			<xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="msg-header-2_0.xsd"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/ws/2002/12/secext" schemaLocation="wsse.xsd"/>
			<xsd:import namespace="http://services.sabre.com/STL/v01" schemaLocation="STL_For_SabreProtocol_v.1.2.0.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="HotelRateDescriptionInput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="header2" element="wsse:Security"/>
		<wsdl:part name="body" element="sws_xsd:HotelRateDescriptionRQ"/>
	</wsdl:message>
	<wsdl:message name="HotelRateDescriptionOutput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="header2" element="wsse:Security"/>
		<wsdl:part name="body" element="sws_xsd:HotelRateDescriptionRS"/>
	</wsdl:message>
	<wsdl:portType name="HotelRateDescriptionPortType">
		<wsdl:operation name="HotelRateDescriptionRQ">
			<wsdl:input message="sws:HotelRateDescriptionInput"/>
			<wsdl:output message="sws:HotelRateDescriptionOutput"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="HotelRateDescriptionSoapBinding" type="sws:HotelRateDescriptionPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="HotelRateDescriptionRQ">
			<soap:operation soapAction="HotelRateDescriptionLLSRQ"/>
			<wsdl:input>
				<soap:header message="sws:HotelRateDescriptionInput" part="header" use="literal"/>
				<soap:header message="sws:HotelRateDescriptionInput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="sws:HotelRateDescriptionOutput" part="header" use="literal"/>
				<soap:header message="sws:HotelRateDescriptionOutput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="HotelRateDescriptionService">
		<wsdl:port name="HotelRateDescriptionPortType" binding="sws:HotelRateDescriptionSoapBinding">
			<soap:address location="https://webservices.havail.sabre.com/websvc"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>