<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:eb="http://www.ebxml.org/namespaces/messageHeader" xmlns:or="http://services.sabre.com/res/or/v1_9" xmlns:ota="http://webservices.sabre.com/sabreXML/2003/07" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:stl1="http://webservices.sabre.com/pnrbuilder/v1_16" xmlns:stl2="http://services.sabre.com/STL/v01" xmlns:tns="http://webservices.sabre.com/pnrbuilder/getres" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetReservationWSDL" targetNamespace="http://webservices.sabre.com/pnrbuilder/getres">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="msg-header-2_0.xsd"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/ws/2002/12/secext" schemaLocation="wsse.xsd"/>

			<xsd:import namespace="http://webservices.sabre.com/pnrbuilder/v1_16" schemaLocation="PNRBuilderTypes_v1.16.0.xsd"/>
			<xsd:import namespace="http://webservices.sabre.com/pnrbuilder/v1_16" schemaLocation="GetReservationSTLRQ_v1.16.0.xsd"/>
			<xsd:import namespace="http://webservices.sabre.com/pnrbuilder/v1_16" schemaLocation="GetReservationSTLRS_v1.16.0.xsd"/>
			<xsd:import namespace="http://services.sabre.com/res/or/v1_9" schemaLocation="OpenReservation.1.9.0.xsd"/>
		</xsd:schema>
	</types>
	<message name="GetReservationInput">
		<part element="eb:MessageHeader" name="header"/>
		<part element="wsse:Security" name="header2"/>
		<part element="stl1:GetReservationRQ" name="body"/>
	</message>
	<message name="GetReservationOutput">
		<part element="eb:MessageHeader" name="header"/>
		<part element="wsse:Security" name="header2"/>
		<part element="stl1:GetReservationRS" name="body"/>
	</message>
	<portType name="GetReservationPortType">
		<operation name="GetReservationOperation">
			<input message="tns:GetReservationInput"/>
			<output message="tns:GetReservationOutput"/>
		</operation>
	</portType>
	<binding name="GetReservationSoapBinding" type="tns:GetReservationPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<operation name="GetReservationOperation">
            <soap:operation soapAction="GetReservationOperation"/>
			<input>
				<soap:header message="tns:GetReservationInput" part="header" use="literal"/>
				<soap:header message="tns:GetReservationInput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</input>
			<output>
				<soap:header message="tns:GetReservationOutput" part="header" use="literal"/>
				<soap:header message="tns:GetReservationOutput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="GetReservationService">
		<port binding="tns:GetReservationSoapBinding" name="GetReservationPortType">
			<soap:address location="https://webservices.sabre.com"/>
		</port>
	</service>
</definitions>